name: Deploy static site

on:
  workflow_run:
    workflows: ["Node.js CI"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: node.js.yml
        workflow_conclusion: success
    
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name bridgestatus  --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "bridge-status" --name "bridge-status" --resource-group "mlt-boat"
    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
  
